# Generated by Django 5.0.6 on 2025-03-31 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
